knife4j:
  enable: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ry-config?tinyInt1isBit=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  jpa:
    show-sql: true